[ 2025-04-14 23:21:27,296 ] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.0.216:5000
[ 2025-04-14 23:21:27,296 ] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[ 2025-04-14 23:21:32,970 ] 875 app - ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 48, in predict_datapoint
    return render_template('home.html',results=results[0])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:32,974 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:32] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:34,474 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:34,475 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:34] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:35,598 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:35,599 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:35] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:36,242 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:36,244 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:36] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:36,494 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:36,496 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:36] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:37,057 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:37,059 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:37] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:37,228 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:37,229 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:37] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:37,417 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:37,418 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:37] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:37,613 ] 875 app - ERROR - Exception on /predictdata [GET]
Traceback (most recent call last):
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/app.py", line 21, in predict_datapoint
    return render_template('home.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/Users/ishmael/Documents/covid_vaccine_risk/venv/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/ishmael/Documents/covid_vaccine_risk/templates/home.html", line 130, in template
    {% comment %} <html>
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'comment'.
[ 2025-04-14 23:21:37,614 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:37] "[35m[1mGET /predictdata HTTP/1.1[0m" 500 -
[ 2025-04-14 23:21:47,862 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:21:47] "GET /predictdata HTTP/1.1" 200 -
[ 2025-04-14 23:22:27,101 ] 97 werkzeug - INFO - 127.0.0.1 - - [14/Apr/2025 23:22:27] "POST /predictdata HTTP/1.1" 200 -
